### ISSUE TITLE
Removing the text with social media icons

### ISSUE THREAD

**Issue by ptechofficial** [Real-Dev-Squad/website-www#101]
Having only social media icons is a more subtle approach rather than adding a text with them.
Also, add some zoom animation on hover.
![image](https://user-images.githubusercontent.com/64535754/111860708-52e44980-896f-11eb-899f-2ef0a7e64e89.png)

Refer to CodePen Link for more context
https://codepen.io/_rohan09_/pen/mdBqMNq

**Comment by KhushalAbrol** [comment]
I want to work on this issue. Please assign me this

**Comment by KhushalAbrol** [comment]
https://github.com/Real-Dev-Squad/website-www/pull/117 Please review this pull request

**Comment by brandong512** [comment]
I can take this on. Can you please assign this to me?

**Comment by brandong512** [comment]
So I've removed the text and also added a tiny animation on hover for each icon. How does this look?
![social-media-icon-animation](https://user-images.githubusercontent.com/5855338/147342560-9670689a-718d-46ff-8e4b-e5dc6284e32a.gif)
?

**Comment by rohan09-raj** [comment]
> So I've removed the text and also added a tiny animation on hover for each icon. How does this look? ![social-media-icon-animation](https://user-images.githubusercontent.com/5855338/147342560-9670689a-718d-46ff-8e4b-e5dc6284e32a.gif) ?

This looks awesome🔥
What is the width and height you are using (when hover is not there) ??

**Comment by brandong512** [comment]
1- width & height are starting 20px and growing up to 30px in .5 second
2- sure I'll work on that too

**Comment by rohan09-raj** [comment]
@brandong512 
Can you please make it 35px and on hovering it should be 40 or 45px. Whatever looks good to you.
Also, if the icon quality on making it 35px goes down, you can use similar new icons from Google but keep in mind that it should be similar.

**Comment by brandong512** [comment]
Ok sounds good. I'll find some SVG icons and share them with you. That way when they scale they won't any quality

**Comment by brandong512** [comment]
Here are the svg icons I've found, can you confirm that these are similar enough? 
<img src="https://img.icons8.com/fluency/48/000000/instagram-new.png"/>
<img src="https://img.icons8.com/color/48/000000/facebook-new.png"/>
<img src="https://img.icons8.com/color/48/000000/twitter--v1.png"/>
<img src="https://img.icons8.com/color/48/000000/linkedin.png"/>

**Comment by rohan09-raj** [comment]
@brandong512 Yes, they look good and are very similar to the icons we have. Go ahead with them.

**Comment by brandong512** [comment]
Here is the animation with stable sections so they don't affect the elements around. Also, the logos were changed to be starting at 35px and growing up to 45px. Let me know what you think

![social-media-icon-animation-larger-stable](https://user-images.githubusercontent.com/5855338/147382468-71b2bfdc-c353-4f88-b3d5-8cb8eaae0ba9.gif)

**Comment by rohan09-raj** [comment]
@brandong512 I have added a link in the description. Please refer to that link. The hover should be specific on the image element and nothing else should be affected. 
Thanks for updating the icons.

**Comment by brandong512** [comment]
I see, thank you for the clarification. I'll go ahead and make those changes.

**Comment by brandong512** [comment]
Ok hopefully this one checks all the boxes 🙂

![social-media-icon-animation-larger-stable](https://user-images.githubusercontent.com/5855338/147394163-bcf3d0f5-d322-471c-ab96-204ce537afe2.gif)

**Comment by rohan09-raj** [comment]
Great 💯, raise a PR, attach this short video to description for both mobile view and desktop view, and write closes #<issue_number>. Now comes the code review part😁.
