### ISSUE TITLE
Set up pre-commit hook for checking formatting

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-www#102]
We need pre-commit hook (which runs before the `git commit` command) to check for formatting problems in the files. This is to be done to ensure we are following consistent formatting throughout the codebase.

We'll be using this package: https://www.npmjs.com/package/pre-commit
Fairly simple to implement. You can read up the documentation for details related to installation and using it.

Script to be added in pre-commit hook: `check`

If you want to work on this issue, please comment down. It can be then assigned to you 🙂

**Comment by rajakvk** [comment]
I like to take this up. Please assign. @swarajpure

**Comment by swarajpure** [comment]
#104
