### ISSUE TITLE
Remove option from navbar

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-www#112]
Remove references to "EmberJS Site" from navbars(there can be multiple pages having it)

![image](https://user-images.githubusercontent.com/1935403/120884308-4d25f980-c597-11eb-922e-072e940f3738.png)

**Comment by Shivamyana19** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by swarajpure** [comment]
> I would like to work on this issue. Please assign it to me.

Done!

**Comment by ankushdharkar** [comment]
@Shivamyana19 Consider joining our discord server: https://discord.gg/sXazaRz6, to get your own https://members.realdevsquad.com/ profile :)

**Comment by Shivamyana19** [comment]
I have created a pull request . Please review it.
