### ISSUE TITLE
Maintaining similar navbar in events page as welcome page

### ISSUE THREAD

**Issue by harshith-venkatesh** [Real-Dev-Squad/website-www#114]
Currently welcome page navbar looks like this 
![image](https://user-images.githubusercontent.com/44545218/120924953-e9fda980-c6f3-11eb-9ca6-9419349ec880.png)

and once the user hovers to the event page, we see a different navbar, to maintain the consistency this issue is created.
![image](https://user-images.githubusercontent.com/44545218/120924960-f4b83e80-c6f3-11eb-9047-78065831e9c9.png)

The link to source code events page is below
[Events.html Page](https://github.com/Real-Dev-Squad/website-www/blob/develop/events.html)

**Comment by Aditi-Singh16** [comment]
I have solved this issue, please review it. :)
