### ISSUE TITLE
Create art creator feature

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-www#116]
Whatever you type on the left hand side box shows up on the right side.
This task already has two PRs associated with it. Check [here](https://github.com/Real-Dev-Squad/website-www/pull/145) and [here](https://github.com/Real-Dev-Squad/website-www/pull/143).

[Figma Link](https://www.figma.com/file/bbT6ouwsrjYzs6G4XDSn3a/CSS-Art?node-id=0%3A1)

**Comment by ToBuild-2021** [comment]
commenting to get the task assigned.

**Comment by ankushdharkar** [comment]
@ToBuild-2021 I have assigned you this existing issue: https://github.com/Real-Dev-Squad/website-dashboard/issues/33

You should join our discord server to stay more in touch (it's free): https://discord.gg/sXazaRz6

**Comment by ToBuild-2021** [comment]
yeah 
Working on that .
