### ISSUE TITLE
Create a CONTRIBUTE.md file. 

### ISSUE THREAD

**Issue by Vividh25** [Real-Dev-Squad/website-www#121]
Beginners face issues in forking the code and raising PRs. Adding a contribute.md file would help fix this problem. It should contain how to fork and clone repositories, raise PRs and the steps to be followed while making the PRs. Something similar to [this](https://github.com/Real-Dev-Squad/website-my/blob/develop/CONTRIBUTING.md).

**Comment by VaradAC** [comment]
I would like to take this task.

**Comment by Vividh25** [comment]
Make it like the one mentioned in the link. Also add the content of this photo in the end:  
![prRules](https://user-images.githubusercontent.com/61474917/122507074-2a76f480-d01d-11eb-853a-c7203041c3bd.PNG)

You'll be using markdown in this task, so get familiar with it.
