### ISSUE TITLE
Add `check` script to GitHub actions

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-www#127]
More info: https://github.com/Real-Dev-Squad/website-welcome/issues/132

**Comment by swarajpure** [comment]
Reserved for internal member

**Comment by swarajpure** [comment]
Do not touch the existing code, just add another block of code in `jobs` as per the yml file mentioned in the link above

**Comment by himanshukm2301** [comment]
I'll take this up

**Comment by rohan09-raj** [comment]
Closing this issue as the Linked PR is already merged
