### ISSUE TITLE
Fix the member animation 

### ISSUE THREAD

**Issue by Vividh25** [Real-Dev-Squad/website-www#135]
**Bug**: The member animation in the page suddenly jumps back to the starting state when a particular part of the screen is scrolled and doesn't feel very smooth. Look at the attached video for more clarification. 

https://user-images.githubusercontent.com/61474917/125414159-d54be247-ae84-4770-93ab-4e791b521332.mp4

**Comment by rahilkapoor** [comment]
Assign this to me, will try to fix it.
