### ISSUE TITLE
Add content about our community

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-www#139]
Our landing page should have enough information about who we are, so that we can:
- Convince new people who may not be sure what they gain from joining us
- How to reach out to us to join
- Prospective employers get a sense of why our squad is so kickass

Follow good accessibility practices:
- https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html
- https://www.w3.org/TR/wai-aria-practices/examples/landmarks/main.html

Design: [Figma Link](https://www.figma.com/file/x8qP34HniYSjJGf7iyCOkj/Main-Page-Important-content?node-id=0%3A1)

**Comment by rohan09-raj** [comment]
@swarajpure Can u please assign it to me?
