### ISSUE TITLE
Standardize Navbar across Real Dev Squad

### ISSUE THREAD

**Issue by rahilkapoor** [Real-Dev-Squad/website-www#161]
### Design of New Navbar:
https://www.figma.com/file/bpFHG9hXM13GSLmTkoNsrF/Navbar?node-id=0%3A1

## Few Details 
- font : Roboto
- weight: 700
- active color : #88D870
- hover color : #88D870
- size : 16 px (try making it in rem)
- active underline height : 3px (color : #88D870)
- RDS Logo Size - 50x50

### Pay Attention
=> Underline should be under the text as shown in the image and not inside the container in which the text persists.
=> Underline should be only under the active tab, it should not be visible on hover.
=> For this site Events/Img tag(rds logo) both should be configured properly!
=> The full navbar should be changed to the toggle menu when the screen width is less than 970px.

**Comment by Aryan-9211** [comment]
I want to work on this.
