### ISSUE TITLE
Navigate to `my.realdevsquad.com`

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-www#162]
If someone clicks on `Hello, <username> and profile picture`, the user should be taken to https://my.realdevsquad.com/profile
![image](https://user-images.githubusercontent.com/46373689/146671415-2916717a-1354-4de9-9b4d-37a537fa29d5.png)

**Comment by ShivamPali-2020** [comment]
Hi @swarajpure can you assign this issue to me?

**Comment by swarajpure** [comment]
> Hi @swarajpure can you assign this issue to me?

All yours!

**Comment by harshith-venkatesh** [comment]
The above PR is closed as there are no developments after the request

**Comment by rajat-mehra05** [comment]
Would like to work on this issue if it's still open.

**Comment by rohan09-raj** [comment]
> Would like to work on this issue if it's still open.

@rajat-mehra05 Sure, assigning it to you.
