### ISSUE TITLE
Fixing the contrast and centering in user greeting 

### ISSUE THREAD

**Issue by Vividh25** [Real-Dev-Squad/website-www#170]
![rdsbug](https://user-images.githubusercontent.com/61474917/139715914-f026ef94-4496-4f0d-87c7-bcb2ca042ae3.PNG)

![wwwbug](https://user-images.githubusercontent.com/61474917/139789022-a248b92c-c8ff-4837-beea-bcb30d0dd72d.jpg)
To do:- 
- [ ] Change the user greeting text color to white.
- [ ] Center the user greeting in both full screen and mobile version.

**Comment by iRahulP** [comment]
@Vividh25 , Can I work on this one?

**Comment by Vividh25** [comment]
> 
> 
> @Vividh25 , Can I work on this one?

Assigned. I have updated the issue. Do have a look once.
