### ISSUE TITLE
Fix content alignment

### ISSUE THREAD

**Issue by Vividh25** [Real-Dev-Squad/website-www#173]
The content on the main page breaks during a certain width range

![wwwbug](https://user-images.githubusercontent.com/61474917/141669653-85d31d43-75ed-425d-a0db-bddac20c8e0b.PNG)
.

**Comment by nguyenhung15913** [comment]
Can I work on this?

**Comment by rohan09-raj** [comment]
> Can I work on this?
Sorry we forgot to close the issue.
Actually, the issue has been resolved, and there were slight fixes which is covered in the another issue that has already been taken by someone.
