### ISSUE TITLE
Fix the content margin/padding

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#176]
![image](https://user-images.githubusercontent.com/78433013/145208563-434a8bed-d3dd-4f7e-ace7-eec877ababb6.png)

Screen Size - 1100 x 1125 px
Please make the content responsive in various screen sizes

**Comment by Yogeshp0012** [comment]
Hi @rohan09-raj , I would like to work on this

**Comment by Yogeshp0012** [comment]
The pull request has been created. Please check it :-)
