### ISSUE TITLE
Navbar GitHub login button flickering issue for Signed In user

### ISSUE THREAD

**Issue by shubham-y** [Real-Dev-Squad/website-www#182]
The Sign In button is visible initially before displaying the greeting message and profile picture for a signed-in user for both the Desktop and mobile view

Check the video for reference

https://user-images.githubusercontent.com/46373689/146391348-bdf034fb-dff1-4df4-91b3-1aadedd463bb.mp4

**Comment by Aryan-9211** [comment]
I want to work on this issue.
