### ISSUE TITLE
Bug: link not working on wide screens

### ISSUE THREAD

**Issue by rajat-mehra05** [Real-Dev-Squad/website-www#187]
1. Anchor tag doesn't work on screens which have `width > 970px` which restricts users to redirect to their `profile` page.
2. Works for screens having `width <= 970px`.
3. In the screenshot attached, the screen width is up to `970px`. Link works up to this width.

![image](https://user-images.githubusercontent.com/35677839/147330163-a3e76108-bda8-4e21-96f0-0ac0ab8266f0.png) 

I want to work on this issue too as well.

**Comment by rohan09-raj** [comment]
@rajat-mehra05 Closing this issue as this issue can be addressed in the PR #188.
