### ISSUE TITLE
Fix footer and padding on hovering over links

### ISSUE THREAD

**Issue by rajat-mehra05** [Real-Dev-Squad/website-www#197]
Issues to be fixed: (first pic)
1. Footer can be made bold to make it readable
2. Add padding to event links so that on hovering over them, the background has padding.
![image](https://user-images.githubusercontent.com/35677839/148262860-f76573bb-c350-4fba-83d8-4d52bf2f8efe.png)

**Comment by swarajpure** [comment]
We shouldn't be adding/chaning padding on hover, that'll cause other elements to shift from their natural position, which doesn't look really nice
We could either make the text being hovered either bold or change its color or add shadow or underline or something
Hope that makes sense, let me know if you've any doubts!

**Comment by rajat-mehra05** [comment]
> We shouldn't be adding/chaning padding on hover, that'll cause other elements to shift from their natural position, which doesn't look really nice We could either make the text being hovered either bold or change its color or add shadow or underline or something Hope that makes sense, let me know if you've any doubts!



> We shouldn't be adding/chaning padding on hover, that'll cause other elements to shift from their natural position, which doesn't look really nice We could either make the text being hovered either bold or change its color or add shadow or underline or something Hope that makes sense, let me know if you've any doubts!

Yes, I agree. But I have added padding to the links text and not while on hovering over the links. That won't affect the natural position of any element. I have already taken your point in consideration while making the changes.

**Comment by swarajpure** [comment]
> 2\. On hovering, need to add padding to make links look better on website

Isn't that a bit confusing then?

**Comment by rajat-mehra05** [comment]
> > 2. On hovering, need to add padding to make links look better on website
> 
> Isn't that a bit confusing then?

My bad, I don't how to explain. I'll probably add a video demo or direct PR for that (whichever option you suggest).

**Comment by rohan09-raj** [comment]
> Issues to be fixed: (first pic)
> 
> 1. Footer can be made bold to make it readable
> 2. On hovering, need to add padding to make links look better on website
>    ![image](https://user-images.githubusercontent.com/35677839/148262860-f76573bb-c350-4fba-83d8-4d52bf2f8efe.png)

2nd point can be `Add some padding to event links, therefore on hover when background changes, it should have some padding.`
