### ISSUE TITLE
Fix width of Logo 

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#203]
Fix width of the logo and make it equivalent to its height
![image](https://user-images.githubusercontent.com/78433013/148438188-ecd4edf3-e88e-4182-8dc4-2cfd05ce0040.png)

**Comment by tacosontitan** [comment]
Tackling this now.

**Comment by rohan09-raj** [comment]
> Tackling this now.

@tacosontitan Thanks for the PR. but please get it assigned to you first then only work on the issues.

**Comment by tacosontitan** [comment]
Please assign this issue to me; I'll take care of the mobile view in the morning.

**Comment by rohan09-raj** [comment]
> Please assign this issue to me; I'll take care of the mobile view in the morning.

Yeah sorry, forgot to assign you. Now, assigned

**Comment by tacosontitan** [comment]
Should I use this same issue for the mobile view? I noticed it was still open after the PR was closed out. Just making sure I don't need to create a new issue for the mobile view fix.

**Comment by rohan09-raj** [comment]
> Should I use this same issue for the mobile view? I noticed it was still open after the PR was closed out. Just making sure I don't need to create a new issue for the mobile view fix.

I have fixed it myself, because this was on production level. So, yeah this is fixed now, closing this issue.

**Comment by MrChinmay03** [comment]
Hey I am interested in this project can u please assign this to me?
