### ISSUE TITLE
[RFC] Subscribe to Newsletter for RDS 

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#208]
We need to start collecting emails for the Events which we organize to have a greater reach and audience. That is why we need this feature to be added. Do you have any other ideas ?? (Please do suggest)
- What fields can we include ?? (`Name` and  `Email`  ||  Only `Email`)
- Where should we place this `Subscribe to NewsLetter` ??
I am thinking of adding it to the landing page just below the `Past Events` Section. 
![image](https://user-images.githubusercontent.com/78433013/148639811-d7c079b3-edcf-4319-a6c8-77fe0071028a.png)

Please put your thoughts on this with the screenshot where it would be better to place it.

Sample Design :
![image](https://user-images.githubusercontent.com/78433013/148639641-9b4da1d1-232e-4d22-baf3-329a5f63331d.png)

**Comment by palakgupta2712** [comment]
We can have only an email id for the newsletter and below the past event will look better.

**Comment by priyanshk20** [comment]
Yes, only e-mail will be better, just below the events section, maybe the font/input-box a bit bigger.

**Comment by rohan09-raj** [comment]
Thanks, @palakgupta2712 and @priyanshk20 for your valuable suggestions.

**Comment by rohan09-raj** [comment]
The final conclusion is we will be keeping only email, and it will be below events on main page.
