### ISSUE TITLE
Cards Design for `Why you should consider joining`

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#209]
### Current Design

We have `Why you should consider joining` something like this
https://www.realdevsquad.com/
![image](https://user-images.githubusercontent.com/78433013/148677222-602cf8b0-52d6-4a0d-8d5c-53111aa93721.png)

### Expected Design

- We will be shifting to cards design, for each point we will have a card. (`Image - 1`)
- On clicking, `Read More` a modal will appear will the complete description of the point (`Image - 2`)

**Image - 1**
![image](https://user-images.githubusercontent.com/78433013/148677306-c0844178-43dc-4bdd-84e9-e8ac4428afc5.png)
**Image - 2**
![image](https://user-images.githubusercontent.com/78433013/148677312-488b94ff-e962-4415-a66b-c6f52fe6f8d5.png)

**Comment by palakgupta2712** [comment]
I'm interested in working on this issue.

**Comment by palakgupta2712** [comment]
New designs: 
![Design 5](https://user-images.githubusercontent.com/61227144/152550323-20b3f876-9700-4d8b-83ce-bd8836223ded.png)

Modal pop up on clicking the `Read more` button
![Group 27 (1)](https://user-images.githubusercontent.com/61227144/152550361-53b91fda-148f-44db-8d78-27269b2eb384.png)
