### ISSUE TITLE
Add scroll to top Button

### ISSUE THREAD

**Issue by 7ORP3DO** [Real-Dev-Squad/website-www#212]
When we are at the bottom of the page, it is difficult for a user to add up and up. Therefore we need a scroll to top floating button.

- **Place:** Bottom Right
- **Button Color:** #1d1283
- **Icon Color:** #fff

**Note:** Make it responsive for all the devices

**Image for Reference**
![image](https://user-images.githubusercontent.com/78433013/149157130-1d62f9a0-6be1-478e-b119-ee4b23b36d71.png)

**Comment by anmoldewanrai** [comment]
Could I take up this one?

**Comment by 7ORP3DO** [comment]
@rohan09-raj vro, I had already mentioned in the last line of the description that I want to work on this issue.  🙄

**Comment by rohan09-raj** [comment]
> @rohan09-raj vro, I had already mentioned in the last line of the description that I want to work on this issue. 🙄

Are you in Real Dev Squad Discord Server ??

**Comment by 7ORP3DO** [comment]
> Are you in Real Dev Squad Discord Server ??

No. What is Discord's server link?

**Comment by 7ORP3DO** [comment]
> Here is the link Prateek https://discord.gg/AbAXH9XN
> 
> I apologize for my mistake, I have previously discussed this issue with the members there in Real Dev Squad and asked them to create the issue. I thought one of them has created it. You can join the discord server, there we do lot of features like these in different frameworks too and you can contribute to any of them

Ok Bro, No problem 🙂
