### ISSUE TITLE
Fix Scroll to Top Button

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#221]
At current, the scroll to top button is visible all the time even if we are at the top of the page.
- It should only be visible after the initial scroll.

Try adding a transition or animation to  scroll to top button when it appears and disappear
![image](https://user-images.githubusercontent.com/78433013/149945633-b40c1a21-2f54-4d6f-9201-b5f5ddb0d792.png)

**Comment by 7ORP3DO** [comment]
Hii I want to work i this issue.

**Comment by dhanush027** [comment]
Can I take this task

**Comment by rohan09-raj** [comment]
> I want to work on this issue.

@7ORP3DO Can I know from which account you are in discord server of Real Dev Squad ??

**Comment by rohan09-raj** [comment]
> Can I take this task

Uh oh!, first come first serve

**Comment by riiyaaa** [comment]
Can I take this issue!!

**Comment by DeRaowl** [comment]
@rohan09-raj let me know if I can take this issue.
