### ISSUE TITLE
Store colors in different CSS file

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#228]
- Make a separate CSS file named `global-variables.css`
- Store all the colors we use across the repository in that file
- Use CSS variables for the same

**Note :** Follow the conventions and variable names should be like `--color-navy-blue: #1d1283`

**Comment by ipriyankdev** [comment]
Please assign it to me!

**Comment by akash2819** [comment]
Please assign me

**Comment by Shashwat61** [comment]
I would like to take the task!

**Comment by rohan09-raj** [comment]
> I would like to take the task!

@Shashwat61 Already assigned to Akash
