### ISSUE TITLE
Art Feature Improvements

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#229]
- [x] Make the Page Responsive
- [x] Add Instructions for making the Art. 

**Link for the Page**
https://www.realdevsquad.com/art-feature.html
![image](https://user-images.githubusercontent.com/78433013/151816613-988d495b-63b7-436d-b350-195ce3c4e04b.png)

**Note:** 
1- Instructions should be hidden at first and on clicking a button or icon there will be a box that will contain all the rules, examples, and instructions.
2- The colors you will be using are only the existing colors that we have.

**Instructions Example :**
![chrome-capture](https://user-images.githubusercontent.com/78433013/151815417-ef630824-e6f7-4d1b-9065-9d19202ca4e3.gif)

**Sample Art :**
![image](https://user-images.githubusercontent.com/78433013/151813178-8e35b634-edb1-4a10-94ea-1a3184c9b9f9.png)

**Comment by Kshashank99** [comment]
Assign it to me

**Comment by rushabh-t** [comment]
I would like to work on it
