### ISSUE TITLE
Refactor HTML and Folder Structure

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#239]
Structure of Files
- Use iframes for dividing the HTML files
- Sections of index.html
  - Navbar should be in different HTML file
  - Remove Banner (1year anniversary
  - Description should be different HTML file
  - Upcoming Features, Past events, Upcoming events should have in different section tags
  - Footer should contain `To know about` text and `Repo link`
  
  ETA : 21st February, 2022 EOD

**Comment by aman7870** [comment]
Submitted a working PR #242 for fixing folder structure

**Comment by aman7870** [comment]
@rohan09-raj done with the changes. Please have a look

**Comment by rohan09-raj** [comment]
Site is being migrate to Ember, therefore no need of the refactor
