### ISSUE TITLE
Descriptive Card Improvements

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#246]
### Current Scenario
- If user hovers on the card they cannot click it, the click is limited to `read more` button.

![chrome-capture-2022-3-17](https://user-images.githubusercontent.com/78433013/163688343-df7e3b8b-bd8f-4bdd-b465-3cd433906513.gif)

### Expected Scenario
- User should be able to click on the whole card instead of just `read more` button to open the modal

### Further Improvement
- [x] Move the close icon to the right
- [x] Remove extra margin or padding to make it look good

![image](https://user-images.githubusercontent.com/78433013/163688204-1dd6a522-9e29-4652-ae77-6b529d69ad5b.png)

**Comment by heyrandhir** [comment]
I would like to take this up. Please assign it to me.
