### ISSUE TITLE
Subscribe to Newsletter  - User Interface Improvements

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#247]
## Current State
- Design is not responsive at some points in screen width
- Additional content is also there which sounds like a marketing strategy
![image](https://user-images.githubusercontent.com/78433013/167111704-7da9e058-a5ab-48a2-83f2-0eec945ed430.png)

Check the existing design live here :
https://staging-realdevsquad.netlify.app/

## Task
 - Modify the content according to the Figma design below
 - Make the design responsive as provided in Figma.
https://www.figma.com/file/lZ98EsdCM9ueZ9ghzcnACH/Newsletter?node-id=0%3A1

**Comment by rohan09-raj** [comment]
@palakgupta2712 
Don't you think that existing design is already good with some minor tweaks
![image](https://user-images.githubusercontent.com/78433013/164173679-f4f19fb9-5cd1-49ed-a90f-13e8ef0f4ff7.png)

**Comment by rohan09-raj** [comment]
DESIGN : 
Initial Design
![subcribeForm](https://user-images.githubusercontent.com/61227144/163844848-b01cdbe0-3c18-4685-b475-d060aee9f9fc.png)

Input box focused 
![inputboxFocused](https://user-images.githubusercontent.com/61227144/163844766-3d92163a-c591-4d75-bd29-c847bbbecd34.png)

Button on hover
![subsrcibe](https://user-images.githubusercontent.com/61227144/163844724-50376461-aac7-4ced-b9f8-d796df0ec737.png)

color used - 
for button - #163588
for button hover - #e20665
for input focused - #f5c4f1

**Comment by Prateekgaur** [comment]
I would like to take this task please assign it to me

**Comment by vvaibhavdesai** [comment]
@rohan09-raj it would be great if we add the link of figma for this design & also make sure that we have added the responsive design also to the file.

**Comment by rohan09-raj** [comment]
> @rohan09-raj it would be great if we add the link of figma for this design & also make sure that we have added the responsive design also to the file.

Yeah sure, will create it with all the details mentioned in figma

**Comment by Rohitprasad004** [comment]
HTML CODE:-

<article class="product">
  <div class="a">Get Event Notification right in your inbox</div>
  <div class="ss">
  <div class="b">Email Address</div>
  <input class="c" type="email" name="mygmail" required>
  <button class="d">SUSCRIBE</button>
  </div>
</article>

CSS CODE:-
.a{
  font-weight:bold;
  font-size:28px;
  text-style:sans-serif;
  margin-bottom: 22px;
  font-family: 'Roboto', sans-serif;
}
.b{
   font-weight:bold;
  font-size:14px;
  font-family: 'Roboto', sans-serif;
  color: #343a40;
  margin-bottom:5px;
}
.c{
  height:40px;
  width:332px;
  border: 2px solid black;
  border-radius:4px;
}
.ss{
  margin-left:6px;
}
.d{
  height: 46px;
  width: 130px;
  font-weight:bold;
  border-radius: 4px;
  color:white;
  background-color:#302f97;
}

**Comment by aakankshadhurandhar** [comment]
@rohan09-raj  Can you assign me this issue ?
