### ISSUE TITLE
Change Color for Navbar in Dark-Mode [Mobile View]

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#248]
In the navbar.css, on line 126 change the CSS variable name from `--color-dark-blue` to `--color-nav`

To enable Dark Mode :
Run this code in console (developer tools)
```
document.cookie = 'theme=dark';
window.location.reload()
```

**Comment by RahulGoyal-tech** [comment]
Assign this to me.

**Comment by shawchandankumar** [comment]
Assign me
