### ISSUE TITLE
Change `src` URL for Member's wheel images

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#255]
## Current Scenario
We are fetching images of 5 random members every time we do a call to `/members` API. But the images are of varied sizes/resolution
For example : One Image is of resolution `700 x 650` and the other image can be of resolution `450 x 560`
```
res.cloudinary.com/realdevsquad/image/upload/v1645293071/profile/XAF7rSUvk4p0d098qWYS/ovew4w7n6zdmgy03yr3z.png
```

## Expected Scenario
The above scenario can be fixed adding a small query to the URL i.e. `/w_200,h_200` as it is in the URL.
```
res.cloudinary.com/realdevsquad/image/upload/w_200,h_200/v1645293071/profile/XAF7rSUvk4p0d098qWYS/ovew4w7n6zdmgy03yr3z.png
```

**Comment by brandong512** [comment]
I can take this issue, can you please assign it to me?

**Comment by rohan09-raj** [comment]
@brandong512 Assigned you
