### ISSUE TITLE
Join Section | UX Improvements

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-www#298]
### Issue

The join section has a few issues which hinder the user experience and may cause chaos for users while filling them.
**Files that will change**
- `js/join.js`
- `css/join.css`
- `/join.html`

### Description:

The join section is live at [Real Dev Squad | Join](https://realdevsquad.com/join.html).
While browsing through the section we found some issues listed below:

- [x] **Data validation:**
  - **Current behavior**:  The validator runs and sets the background color of all the input fields to red `as soon as the page loads.`
  - **Expected behavior**: The validator should run and set the background color `when the user starts entering the data`.
  
 - [x] **Display word limit:**
   - **Current behavior**: There is no word limit/ words left shown in any input field.
   - **Expected behavior**: The UI must show how many words are left while they are providing their input.
   
 - [x] **Dropdown for location:**
   - **Current behavior**: The form currently accepts any data in location fields.
   - **Expected behavior**: As soon as the user starts entering the data they should get a dropdown to select from.
   
 - [x] **Placeholders:**
   - **Current behavior**: None of the input fields currently have a placeholder.
   - **Expected behavior**: All the input fields must have a placeholder.
   
 - [x] **Correct and incorrect data indicator:**
   - **Current behavior**: When the data is correct the background of the input field changes to green. In case of incorrect data, it is red.
   - **Expected behavior**: When the data is correct just remove the red color rather than adding the green background.

 - [ ] **Focus on a field:**
   - **Current behavior**:  The user lands on the page/clicks the next page the page just appears and none of the input fields have a cursor
   - **Expected behavior**: As soon as the user lands on any page of the join section the cursor must be present in the first / previously entered input field.

**Comment by samarpan1738** [comment]
Validation errors at field level should also be visible below the input label

**Comment by RitikJaiswal75** [comment]
> Validation errors at field level should also be visible below the input label in red color

yes @samarpan1738 that is what I meant by display word limit, Please checkout the PR that I have raised it contains the video for the same
