### ISSUE TITLE
Disable redirecting to `github.realdevsquad.com`  

### ISSUE THREAD

**Issue by prakashchoudhary07** [Real-Dev-Squad/website-www#301]
Disable redirecting to `github.realdevsquad.com` as `Deceptive site ahead` is being shown

This is being done here https://github.com/Real-Dev-Squad/website-www/blob/e73fbee0a16b059a5e8fd83a2851af6a930a94ec/js/index.js#L70-L74

**Comment by prankurnov15** [comment]
I am assigning  this to @prankurnov15 (myself)

**Comment by prankurnov15** [comment]
#308 is removed due to some technical issues on my machine raised the #309 as constant fix .
