### ISSUE TITLE
Enhance the new /join page

### ISSUE THREAD

**Issue by Neenu-12** [Real-Dev-Squad/website-www#337]
The input boxes look disabled currently, we need to make them look usable.

![abc](https://user-images.githubusercontent.com/74719713/205987597-95bcc42e-2d47-4eb1-89a6-5280bded5970.png)

**Comment by Neenu-12** [comment]
@ankushdharkar , as you asked I have created the issue. Please assign it to me and provide me the details what the end output should look like.

**Comment by Neenu-12** [comment]
@ankushdharkar Please provide some clarification on the issue.

**Comment by Neenu-12** [comment]
@ankushdharkar Please provide me the design so that I can start working on the issue 😄

**Comment by ankushdharkar** [comment]
@Neenu-12 Please use this as the mocks. Readjust the web design accordingly please. Let me know if you have further questions. Thanks!

![temp](https://user-images.githubusercontent.com/1935403/209452382-aac1e7cb-b373-4032-abcc-a8a6c96bc495.jpg)

**Comment by Neenu-12** [comment]
Thanks @ankushdharkar , will start working on it.
