### ISSUE TITLE
Broken link when clicking on logo icon on home page

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-www#353]
## Issue: Broken link when clicking on logo icon on home page

**Steps to reproduce:**

1. Go to the home page of the website url is (https://www.realdevsquad.com/)
2. Click on the logo icon in the top left corner

**Expected behavior:**
The link should take the user to the home page or to the designated landing page for the website.

**Actual behavior:**
The link is broken and does not take the user to the intended page. and it is opening nonfunctional link(#).

**Solution:**

- The link should be changed to the home page of the website. if the user clicks on the logo icon, it should take the user to the home page of the website.

**Comment by rohan09-raj** [comment]
Thanks for fixing the issue.
