### ISSUE TITLE
Signed in user not displayed

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-www#356]
To start the join steps, a user has to be signed in. The join page doesn't show the signed in status

![RDS-Issue-not-signed-in@2x](https://user-images.githubusercontent.com/1935403/209451303-14f2a6d3-96a9-4b5b-acc4-7dbec8728d47.png)

Should look like other pages that show signed in status. E.g
<img width="195" alt="image" src="https://user-images.githubusercontent.com/1935403/209451309-0fbd205c-9258-46a8-adca-19a44c4349df.png">

**Comment by sahsisunny** [comment]
Issue has been solved and also merged (PR #360 ) in develop branch
