### ISSUE TITLE
Dropdown click not working

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#362]
I wanted to share one small issue in our main page(www-site) navigation bar. 
So in the navbar's dropdown my profile link click is only working when clicking on the text. In hovered area click is not working (image for reference).

![image](https://user-images.githubusercontent.com/85296770/210090004-d48578cf-33ce-4cc0-8b57-f6f43115a92d.png)

PS - For sign out it is working.

**Comment by samyakshah3008** [comment]
I would love to work on this issue, can you please assign me?

**Comment by Vaibhav2711** [comment]
Can you assign this issue to me

**Comment by crater90** [comment]
can you assign this to me ?

**Comment by prerana1821** [comment]
I would like to work on this issue.

**Comment by satyam73** [comment]
> I would like to work on this issue.

Sorry @prerana1821 it's first come first serve basis so assigned to @crater90 .
