### ISSUE TITLE
[Ember-Migration] Create a 404 Page

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#371]
## Issue
- We don't have a not found page present and if someone visits any unavailable route they get error of Unrecognized URL
![image](https://user-images.githubusercontent.com/78433013/210358064-b442c377-67b4-4637-97c0-f981047f73a1.png)

## Solution
- Create a 404 page using `ember generate route 404` command. For reference : https://guides.emberjs.com/release/routing/defining-your-routes/
Code Reference : Refer to this issue and the linked PR with it https://github.com/Real-Dev-Squad/website-my/issues/324
Live Reference: https://my.realdevsquad.com/404

- Write Tests for it (Mandatory) - Refer to other files
- Navbar and footer should be present with the rest of the page

## Note 
- PR should be raised to `develop-ember` not `develop`
- Please follow the CSS patterns like BEM in class names and use CSS Modules. Refer to the existing code
- Also, use the information above to write the code.

**Comment by shubhamsigdar1** [comment]
Hi I want to take this task
