### ISSUE TITLE
[Ember-Migration] [Tests] Footer

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#372]
## Issue
- Write tests for the footer component - For reference, refer other files of tests

## Note
- PR should be raised to `develop-ember` not `develop`
- Create a separate branch `test/footer` from `develop-ember` and write the tests in `footer-test.js`

**Comment by AK-Baghel** [comment]
Yes, I want to work on this issue.

**Comment by samyakshah3008** [comment]
I would like to work on it!

**Comment by shmbajaj** [comment]
@rohan09-raj Assign this issue to me, as it seems work is not started yet.

**Comment by manish591** [comment]
Please assign this issue to me.
