### ISSUE TITLE
[Ember-Migration] Stop CI Jobs on Push

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#375]
## Issue
- Currently the jobs run on Pull Request and Push both but it is redundant to run it for both.

## What to do
- Stop the jobs from running on Push
- File Structure 
**Branch :** develop-ember -> `.github` -> `workflows` -> `continuous-integration.yml`

## Note
- PR should be raised to `develop-ember` not `develop`
- After cloning the repo checkout to `develop-ember` first and then create a new branch from develop-ember to work on the issue

**Comment by bhtibrewal** [comment]
can u assign it to me?
