### ISSUE TITLE
[Ember-Migration] Create the join details section on landing page

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#383]
## What to do?
- This should created just below the `What is Real Dev Squad` section
- Create a component using the command `ember generate component join-section`
- For its component class, use `ember generate component-class join-section`
- Create a CSS Module file with the same name and add it to app.css
- Write the component, its CSS and the actions if needed
- Write tests for the same in the created test file.
- Make sure to make the content responsive with respect to other components (refer other files for font size)
- Use Media Queries from these defined values (1250px, 1024px, 768px, 625px, 425px), if needed

## Figma Design
https://www.figma.com/file/5Tk9bgA7DXchDtCdrrPSwD/Main-Site?node-id=503%3A20&t=hgWPgx0Q9Zb0bBHj-0

## Note
- Checkout to `develop-ember` and create a branch from `develop-ember`
- PR should be made to `develop-ember`

**Comment by shmbajaj** [comment]
@rohan09-raj please assign this issue to me.

**Comment by Neenu-12** [comment]
@shmbajaj I'm currently working on it.
