### ISSUE TITLE
[Ember-Migration] Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#384]
## What to do
- Create a CONTRIBUTING.md similar to this https://github.com/Real-Dev-Squad/website-my/blob/develop/CONTRIBUTING.md
- Replace the screenshot this repo screenshot
- Replace `website-my` with `website-www`
- Replace `develop` branch with `develop-ember`

**Comment by Dev-AkshatGupta** [comment]
Can you assign this to me?

**Comment by Dev-AkshatGupta** [comment]
Its been done please review this [PR`](https://github.com/Real-Dev-Squad/website-www/pull/385). Thanks
