### ISSUE TITLE
Fix Join Section on Main Page

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#391]
## What to do?
- Fix the join button click issue
![image](https://user-images.githubusercontent.com/78433013/212855646-a540bcb7-625d-4725-8d18-d88c24289253.png)
![image](https://user-images.githubusercontent.com/78433013/212854670-2656834a-73af-4d9f-a523-0675e9cc8f0e.png)

- Change the font size of the description to `16px` or `1rem` and fix the spacing between elements
![image](https://user-images.githubusercontent.com/78433013/212855890-3a7702bd-e23f-4751-8a16-fff5131251b8.png)

**Comment by sohamsshah** [comment]
Hi, I would like to work on this issue. Is it possible to be assigned it to me?
