### ISSUE TITLE
[Ember-Migration] Back button optimization with Query and Params

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#403]
## Issue
- Currently, when we visit `/join` and move to other steps
- Then if we click browser `Back` button it goes to `/` route
- But the expectation here and a good UX is we should be directed to the previous page where user comes from.

## Suggested Solution
- We can use query params for e.g. -> `realdevsquad.com/join?step=1`
- Also, we can look for other solutions as well.

**Comment by shmbajaj** [comment]
@rohan09-raj please assign this issue to me.

**Comment by sahsisunny** [comment]
Merged in PR - #408
