### ISSUE TITLE
[Ember-Migration] Scroll bar disabled on index page

### ISSUE THREAD

**Issue by Neenu-12** [Real-Dev-Squad/website-www#406]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/74719713/219117863-773f8aea-3315-4695-bca7-2fb4d96f8fc1.png">

We currently don't have scroll bar enabled on the website.

**Comment by danishhansari** [comment]
Hey Dev, I would like to work on this issue would you please share a bit context about what i need to do in this issue....
