### ISSUE TITLE
Production and preview deployments not working

### ISSUE THREAD

**Issue by RitikJaiswal75** [Real-Dev-Squad/website-www#421]
# Cloudflare pages not deploying the production and preview builds

I raised a PR on 8 March 2023 IST as a part of a hotfix that would remove the signing button from the main site i.e. website-www
My PR was merged and even sync dev to main was merged. But as observed by @rohan09-raj @prakashchoudhary07 and me, we found our builds are not deploying. 

We tried re-deploying a previously deployed instance. That instance showed re-deployment successful but the new changes of the latest PR were not reflected. 

For the preview builds we tried to open the latest preview build which resulted in `NOT Found`

Link to Sync dev to main: [https://github.com/Real-Dev-Squad/website-www/pull/415](https://github.com/Real-Dev-Squad/website-www/pull/415)
Link to the hotfix PR: [https://github.com/Real-Dev-Squad/website-www/pull/414](https://github.com/Real-Dev-Squad/website-www/pull/414)

**Comment by ankushdharkar** [comment]
Looking at CF dashboard, 

This commit is the latest deployed: [aba3bde](https://github.com/Real-Dev-Squad/website-www/commit/aba3bdeb763840c2ab28a60e3bcfc763a1a7cc4d) Merge branch 'develop'
Success
3:01AM March 6, 2023


Not sure why this happened. We have "Enable automatic production branch deployments" enabled for `main` branch. Let's continue keeping an eye on new merges.

Thank you for raising this issue.

**Comment by ankushdharkar** [comment]
Weirder: The preview link generated also doesn't match the commit hash of the stale deployement.

![temp@2x](https://user-images.githubusercontent.com/1935403/223544267-ec023275-8d1b-43ab-816c-7e8f3d16f709.png)

**Comment by ankushdharkar** [comment]
I think the reason for CF pages not working is this: https://discord.com/channels/673083527624916993/749241412830232679/1082766042142617621

The issue has been resolved and latest commit [6b23714](https://github.com/Real-Dev-Squad/website-www/commit/6b23714dc48f387ef67db8ad0ee03ead296e08c5) is now deployed.
