### ISSUE TITLE
[Live-Site] Create the header component for live screen

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#435]
![image](https://user-images.githubusercontent.com/85296770/225785897-dea63883-fddf-4363-93b2-493e88c1e043.png)
> Component to design

Figma Link - https://www.figma.com/file/O8QLwPzTuH3RIWoYdxitln/Live-Page?node-id=0-1&t=Tm6ZyIzHAvbvrMGj-0

**Comment by SanketDhabarde** [comment]
I will start working on this.

**Comment by SanketDhabarde** [comment]
As we are building an existing app. The Navbar will look like this:
As per the requirement:
**Route:** www-v2.realdevsquad.com/live

![Screenshot (392)](https://user-images.githubusercontent.com/40385118/226394250-53ba79a5-ffa6-4317-858a-2e5638bdffa1.png)

**Comment by satyam73** [comment]
> As we are building an existing app. The Navbar will look like this: As per the requirement: **Route:** www-v2.realdevsquad.com/live
> 
> ![Screenshot (392)](https://user-images.githubusercontent.com/40385118/226394250-53ba79a5-ffa6-4317-858a-2e5638bdffa1.png)

Yep but that is the secondary header for live-site

**Comment by SanketDhabarde** [comment]
![Screenshot (396)](https://user-images.githubusercontent.com/40385118/226825573-51bff10c-fbe1-4db6-aeed-612e081b06fe.png)

**Comment by SanketDhabarde** [comment]
Estimation 25/04/23
FE: 3
Total: 3

**Comment by satyam73** [comment]
Completed by https://github.com/Real-Dev-Squad/website-www/pull/446
