### ISSUE TITLE
[Live-Site] Create the sidebar component

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#438]
![image](https://user-images.githubusercontent.com/85296770/225786018-0b0b3d42-393c-41ba-b039-4d8dbebe7419.png)
> Component to create

FIgma link - https://www.figma.com/file/O8QLwPzTuH3RIWoYdxitln/Live-Page?node-id=0-1&t=Tm6ZyIzHAvbvrMGj-0

**Comment by SanketDhabarde** [comment]
Estimation Date: 25/04/23
FE:  5 days @SanketDhabarde
Completion Date: 10/05/23
