### ISSUE TITLE
Updating the Join section.

### ISSUE THREAD

**Issue by fakhruddinkw** [Real-Dev-Squad/website-www#439]
### What is the issue?
Currently, join section has no field, where new member can input how many hours they will contribute in RDS.

### What is the solution?
Updating the join section to include - How many hours per week, a person will contribute.

### Changes in frontend:
-In this we need to add a new input field for hours, which will be number.(between 1-100),
-Add the user input number into local storage, so that the user can continue from where they left from.

### Changes in backend:
-Add a validator to validate the input number, make sure it is between 1-100.
-Make sure the preview button is only visible after all the validation checks have been successful.

**Comment by RitikJaiswal75** [comment]
> Add the user input number into local storage, so that the user can continue from where they left from.
> Add the user input number into local storage, so that the user can continue from where they left from.
the above are from frontend

**Comment by FMK2312** [comment]
OH yes. I will make the change!
