### ISSUE TITLE
Where is the implementation of the the API's

### ISSUE THREAD

**Issue by chirag35847** [Real-Dev-Squad/website-www#451]
HI everyone,
Whenever i fill the form to join the community, it constantly sends me an alert that  `Improper data. Please Re-check the data`, So I cloned the repo and started to dig into code to find out what leads to this message and found out that `https://api.realdevsquad.com/users/self/intro` API is responsible for this, but I couldn't find where is it's implementation.
Therefore I request for help in this

**Comment by fakhruddinkw** [comment]
Can you attach the screenshot?

**Comment by fakhruddinkw** [comment]
so, i have found out the issue @chirag35847 
We have recently introduced a new field in the form you are filling, now what happened is, the validation for the new field is already merged in the backend, but at the frontend the field is still not visible as the PR is still under review.
Meanwhile, i will suggest you contact Ankush directly on twitter if you want to join the community.
Thank you.

**Comment by chirag35847** [comment]
Ok got it, I will contact Ankush on twitter.
Thank you so much for your time
