### ISSUE TITLE
[Join Page] Not able to proceed even after entering all the details

### ISSUE THREAD

**Issue by sumitd94** [Real-Dev-Squad/website-www#458]
There are a couple of improvements needed on the join page

- [ ] When I enter only 2 words in the required fields, it gives me the error message that at least 99 characters are needed, but when I enter more than 99 characters, the error message still stays. Ideally, when I cross 99 characters, the message should disappear and the box color should turn back to white.
<img width="636" alt="Screenshot 2023-04-16 at 10 31 07 PM" src="https://user-images.githubusercontent.com/29303618/232328344-02331ab1-e9be-4f15-8984-aafa5c4ce96e.png">

- [ ] Even though I filled in all the details, the `Next` button is still disabled

**Comment by sumitd94** [comment]
not relevant, my bad.
I got confused with characters and words 😓

**Comment by RitikJaiswal75** [comment]
# Response to Error Message on Join Page

- I apologize for any confusion.
- The error message specifies that 99 more words are needed, not 99 more characters.
- Words are typically separated by spaces.
- It's important to carefully read the error message to ensure that the requirements are met.
- Having a minimum of 100 words was part of the requirements for this feature.
- I appreciate your patience and understanding as we work to resolve this issue.
