### ISSUE TITLE
[Live-Site] Create the panel component

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#462]
![image](https://user-images.githubusercontent.com/85296770/233469691-6a2e21b0-4cf4-4c29-97b0-6a69a820c933.png)
> component to create

Figma Link - https://www.figma.com/file/2VtPGJH61Qp0iarkKW6KTO/Live-Site-Detailed-Designs?node-id=0-1&t=mIdw0NLHXmNrU7Vz-0

**Comment by SanketDhabarde** [comment]
Estimation Date: 25/04/23
FE: 3 days - @SanketDhabarde 
Completion Date: 2/05/23
