### ISSUE TITLE
[Live-Site] Create a modal for joining the live session

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#463]
![image](https://user-images.githubusercontent.com/85296770/234328663-4a4b4d9d-748c-41d1-a6d8-85e28ac26958.png)
> Component to be created

Figma Link - https://www.figma.com/file/2VtPGJH61Qp0iarkKW6KTO/Live-Site-Detailed-Designs?node-id=0-1&t=mIdw0NLHXmNrU7Vz-0

**Comment by SanketDhabarde** [comment]
Estimation Date: 25/04/23
FE: 3 days - @satyam73 
Completion Date: 4/05/23

**Comment by SanketDhabarde** [comment]
![Screenshot (417)](https://github.com/Real-Dev-Squad/website-www/assets/40385118/26b0e426-d24e-4a0f-8828-11dec23edd90)
