### ISSUE TITLE
Missing link on logo in join page

### ISSUE THREAD

**Issue by shubham-y** [Real-Dev-Squad/website-www#464]
On clicking the Real Dev Squad logo on the [join](https://realdevsquad.com/join) page it should redirect to https://realdevsquad.com/

**Comment by UrosKukovic** [comment]
I'd like to solve the issue.

**Comment by shubham-y** [comment]
> I'd like to solve the issue.

Hey @UrosKukovic, are you part of the Real Dev Squad discord community, if yes then ping me in the #new-tasks channel.
If not, then you can join our discord community Real Dev Squad to able to contribute in this issue by visiting this page
https://www.realdevsquad.com/join

**Comment by vishalsingh2972** [comment]
Hey @shubham-y can you assign this to me if it's open?

**Comment by kushvahasumit** [comment]
@shubham-y i ping you on discord in #new-task can you please assign me

**Comment by shubham-y** [comment]
> Hey @shubham-y can you assign this to me if it's open?

Hey @vishalsingh2972,  it seems like you are not part of our discord group.So, you can join our discord community Real Dev Squad to able to contribute in this issue by visiting this page
https://www.realdevsquad.com/join

**Comment by kushvahasumit** [comment]
please review my PR @shubham-y
