### ISSUE TITLE
If redirecting to login than remember the previous page 

### ISSUE THREAD

**Issue by bhtibrewal** [Real-Dev-Squad/website-www#486]
### Issue:
when we are at `/intro?id=` page and if not logged in we get redirected to login and than home 

### Fix: 
after login we should again reach that specific `/intro?id=` page

### Additional Info:
- it's a super user only route, to access it you will either need to setup your local backend and give yourself super_user role, else ask for super_user role on staging

**Comment by Aryex82** [comment]
@bhtibrewal If this is still available, I would like to take this up.

**Comment by Pratiyushkumar** [comment]
@bhtibrewal I would like to take this up

**Comment by Abhay5855** [comment]
@bhtibrewal Can I take this up

**Comment by Abhay5855** [comment]
The setup for frontend and backend is done got the super_user role access today, and can test it out now, ETA for this task will be on Sunday i.e 3/06/23

**Comment by Abhay5855** [comment]
Hey @bhtibrewal The issue is the same for both join and other pages finding a global solutuion for it need some more time the new ETA will be 17/6/23
