### ISSUE TITLE
[Ember-Migration] Remove HTML tags

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#502]
## Issue Description
- Remove the HTML tags from the description of `Why you should consider joiniing?` cards
- Check all the cards description and remove the tags from there

## Image Reference
![image](https://github.com/Real-Dev-Squad/website-www/assets/78433013/9ac88d30-66ef-40b9-ba8c-722d3be6c793)

## Note
- Make a new branch from develop-ember
- Raise the pull request to develop-ember only
- Follow this CONTRIBUTING.md https://github.com/Real-Dev-Squad/website-www/blob/develop-ember/CONTRIBUTING.md

**Comment by Krish-Parekh** [comment]
Can I work on this issue ?

**Comment by divyansh2375** [comment]
i am ready to work on this

**Comment by divyansh2375** [comment]
i have done it but its not showing in PR
