### ISSUE TITLE
[Ember-Migration] Error messages on Step 1, 2, 3 in Join Section Form

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#517]
## Description
- Add the error messages on each field on the Join section Step-1, 2 and 3
- Check the existing functionality here : https://staging-www.realdevsquad.com/join
- It should be similar to the above link only
- Try to use the existing code practices in the project
- Writing/Updating tests is mandatory

### Note:
- Use https://discord.com/channels/673083527624916993/749241412830232679 for any queries/discussion
- Backend setup will ease the development process as the data can be modified and feature can be tested multiple times.
- Otherwise, use `staging-api.realdevsquad.com` to test out the feature
- If any problem in login is there, use https://staging-api.realdevsquad.com/auth/github/login to set the cookie and get logged in

## Design Reference
![image](https://github.com/Real-Dev-Squad/website-www/assets/78433013/6e3d3b32-b589-46da-b045-fd61cb7309fa)

**Comment by pradeepmondal** [comment]
@rohan09-raj Please assign this to me

**Comment by MohitSinghChauhan** [comment]
Pls assign it to me

**Comment by Krish-Parekh** [comment]
Assign me this task
