### ISSUE TITLE
[Ember-Migration] Remove crypto site item from Navbar

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#518]
## Description
- Crypto site is not being used anymore and have some DNS issues
- We can remove the crypto site link and item from the navbar
- Ensure that all the relevant code/constants are removed too
- Fix the events page link to `/events` to render the page correctly, currently only html is rendered

### Note:
- Please use `CONTRIBUTING.md` to start contributing
https://github.com/Real-Dev-Squad/website-www/blob/develop-ember/CONTRIBUTING.md

**Comment by MohitSinghChauhan** [comment]
Pls assign it to me
