### ISSUE TITLE
[New] Change in UI/UX for task card

### ISSUE THREAD

**Issue by iamitprakash** [Real-Dev-Squad/website-www#526]
Description- 
Current 
<img width="779" alt="Screenshot 2023-07-14 at 10 54 33 PM" src="https://github.com/Real-Dev-Squad/website-www/assets/34869115/9382412a-e133-4195-9159-8b307dbf6d2c">
New
<img width="584" alt="Screenshot 2023-07-14 at 11 14 32 PM" src="https://github.com/Real-Dev-Squad/website-www/assets/34869115/1cf0f9e2-c491-4006-acc4-c09c6ce1fdcc">

on click of #TaskNumber of #taskDec
<img width="591" alt="Screenshot 2023-07-14 at 11 44 36 PM" src="https://github.com/Real-Dev-Squad/website-www/assets/34869115/30c9eac5-b5e6-4f1a-9e30-c6bd57a43af7">

Acceptance criteria -
1. Task should look like New Image attached in desc section
2. on click of #TaskNumber of #taskDec new popup should appear like above image
3. on click of right top button i.e. show history will open another/same popup like below screen
<img width="679" alt="Screenshot 2023-07-14 at 11 23 10 PM" src="https://github.com/Real-Dev-Squad/website-www/assets/34869115/738acd2d-ec36-4d88-87d9-f06eb0bd8be8">

Risk - Nothing

Dependency: Database, UI/UX, Backend 

Resource:

**Comment by rohan09-raj** [comment]
Not sure why this issue was created here as this is related to website-status. Hence closing this issue
