### ISSUE TITLE
[Feature flag] Show disclaimer about developer joining process

### ISSUE THREAD

**Issue by ravikumar1002** [Real-Dev-Squad/website-www#532]
**Overview:** 

When developer completed the login and new-signup process then they will come to fill out the joining form but they are not fully aware of the process and what they have to do so, it is important to show a disclaimer about the steps.

Currently, there is only a start button on first page of join form.

**Features point:** 

1. Points to show (first step)
- To join our discord server they have to fill join form which takes hardly 15 minutes.
- The user profile name must be the same as Discord and the website
- Show Privacy Policy We may use their profile photo and name to show them on the RDS website
- He needs to run the `/verify` command to link the RDS discord profile to the website

2. checkbox and enable button accordingly
- User has to select checkbox that they read and accept all the rules
- Makes the Start button usable when the checkbox is selected

https://github.com/Real-Dev-Squad/website-www/assets/86847625/5bccdeeb-e311-4ffd-aaeb-b564816ca424

**Comment by kotesh-arya** [comment]
Closing, as the PR is merged
