### ISSUE TITLE
User profile information form

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-www#54]
When a new user comes to our website, and logins via Github, we redirect them to /goto which then decides where the user was before the login process began, and should take them back there. Currently, /goto always drops the user back to the www site

Upon login via Github for a new user, we create a temporary id for them, we want to change this into an RDS username with certain rules
- Starts with users's first name
- No special characters, except hyphens
- No funky unprofessional words in the username
- Avoid numbers

We want to create a page with a form where a new user can select a username, and fill out or correct their first name, last name, YoE, Company, etc (We can pull in the initial name from Github during login)

We need to create this page to allow new users to sign up to our platform

**Comment by sujitmohanty** [comment]
1. Regex mis-validates username
2. Database setup possibly incomplete.
3. Failure at acquiring desired output when making api calls despite cookie being present.
