### ISSUE TITLE
[Ember-Migration] Add some details in Join start

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-www#574]
## Description
- Add the following content and checkbox in Step - 0 of Join Form (Route: `/join`)
- Enable the start button only when check box is checked otherwise disable it
- Also if the user is not logged in show a toast message 
  - Title - `Requires Login`
  - Content - `Please sign in with GitHub before starting to fill this`
- Check the image for design reference
![image](https://github.com/Real-Dev-Squad/website-www/assets/78433013/8de2b247-b17e-46ca-8ae3-c0a55a1078ea)

**Note:**
For toast library is already integrated, we can utilize that. Reference from other files can be taken

**Comment by Kavita539** [comment]
Hi @rohan09-raj, I would like to work on the issue.

**Comment by shardul08** [comment]
Hi @rohan09-raj, I'd like to work on this.

**Comment by rohan09-raj** [comment]
It is closed due to new onboarding being introduced and developed
