### ISSUE TITLE
Fix: Module not defined while running tests

### ISSUE THREAD

**Issue by samyakshah3008** [Real-Dev-Squad/website-www#632]
## Description: 

- Tests are failing with error: Module not defined 
- Error coming from: https://github.com/Real-Dev-Squad/website-www/pull/611 which was merged before. 

## Screenshots: 

![image](https://github.com/Real-Dev-Squad/website-www/assets/86982322/8ca5e420-ae78-4bbf-b8a0-c435cb19ce56)

**Comment by samyakshah3008** [comment]
Please refer this for help: 
https://stackoverflow.com/questions/64914701/jest-module-not-defined

**Comment by aneenajohn** [comment]
Please assign this to me, I would like to work on this
