### ISSUE TITLE
[Onboarding Flow]-Signup Process for Different User Roles

### ISSUE THREAD

**Issue by shubhamsigdar1** [Real-Dev-Squad/website-www#651]
# Signup Process for Different User Roles
## Overview

Enable "Signup" button for Developers; Implement loader & transition to step-3 on click.
For Maven, Product Manager, or Designer, add "Next" button; Control button states in step-3 with checkbox interaction.

## User stories

1. When a user selects the "Developer" role during signup:
   - The "Signup" button should be visible on the "Signup Details" page.
2. When a user clicks on the "Signup" button:
   - The "Signup" button should be disabled.
   - On step-2, a "Let's Go" button should be visible if user choose developer role else "Join our discord"
3. When a user selects the roles "Maven,"
   - 1 checkbox.(default un-checked, this will be required field) 

5. When a  clicks the checkbox:
   - signup button got enable for user who choose maven role

## Requirement

Wireframe- https://excalidraw.com/#json=YUS5euI0aUYwUKjPWRHIx,ZFMUbJtqXCfK-fYWvXSeHg

![image](https://github.com/Real-Dev-Squad/website-www/assets/107163260/ee2a952c-1027-41ee-9846-89fbf33051a2)

## Acceptance Criteria

- [X] TDD
- [x] For the "Maven" role:
      -  1 checkbox with label get render on signupdetails page
- [x] For the "Developer" role:
      - Clicking the "Signup" button should  disable the button transition to step-2 with a "Let's Go" button.
- [x] For the roles "Maven," "Product Manager," or "Designer":
      - Clicking the "Signup" button should  disable the button transition to step-2 with a "Join our discord" button.
- [x] feature under feature flag

**Comment by iamitprakash** [comment]
@shubhamsigdar1  please update flow diagram as discussed with checkbox placement
