### ISSUE TITLE
[Onboarding Flow]- User Signup Form Validation and Toast Message

### ISSUE THREAD

**Issue by iamitprakash** [Real-Dev-Squad/website-www#654]
# User Signup Form Validation and Toast Message
## Overview:

We need to implement user input validation for the signup form. Specifically, we want to ensure that the input fields for "firstname" and "lastname" meet certain criteria, and if the criteria are not met, display an error message. Additionally, when user is sign out and trying to generate username
should trigger a toast message instructing the user to sign in.

## User Stories:

1. As a user, I want the input fields for "firstname" and "lastname" to:
   - any input not contains spaces.
   - any input not contains non-alphabetical characters.
   - any input not contains numbers.
   - any input not longer than 20 characters.
   - If the input in the "firstname" or "lastname" fields violates any of the above criteria, then display an error message below the input field firstname and lastname if any of the above criteria are not met.
   - If the input in the "firstname" and "lastname" fields meet the criteria, a username should be generated.

2. As a user, when I click the "generateUsername" button and the "sign-in-with-github" session is logged out:
    - A toast message should be displayed, saying "Please sign in."

## Requirement:

Wireframe: https://excalidraw.com/#json=aknBUT8kGMRp2GLESYGcp,NNAIFlOSSeVt-eLbyv51Fw

![image](https://github.com/Real-Dev-Squad/website-www/assets/107163260/17a77ef5-1518-48f3-a995-5052fc36bc9f)

    
## Acceptance Criteria:

- [x] TDD
- [x] Allow user to input anything in "firstname" and "lastname" input field
- [x] If the input in the "firstname" or "lastname" fields violates certain criteria i.e. input not contain spaces, non-alphabetical characters, numbers, more than 20 character, an error message should be displayed below the respective input field ("firstname" and "lastname") and generateusername button will disable
- [x] If the input in both the "firstname" and "lastname" fields meet the criteria, a button will enable and a username should be generated.
- [x] When the "sign-in-with-github" session is logged out, and the "generateUsername" button is clicked
- [x]  A toast message should be displayed with the text "Please sign in."
- [x] feature under feature flag

**Comment by iamitprakash** [comment]
@shubhamsigdar1  looks okay to me

**Comment by vinit717** [comment]
@shubhamsigdar1 Looks good to me let to this parallelly with your next task

**Comment by iamitprakash** [comment]
Looks good @shubhamsigdar1
