### ISSUE TITLE
[Onboarding Flow]- Chaincode Generation Page in Identity Service Setup

### ISSUE THREAD

**Issue by shubhamsigdar1** [Real-Dev-Squad/website-www#670]
# [Onboarding Flow]- Chaincode Generation Page in Identity Service Setup

## Overview: 

In  onboarding flow for the Identity Service setup, we need a  chaincode generation page in step-9 of the join form. This will allow users to easily generate and copy their chaincode.

## User Stories:

- As a user, I need a chaincode generation page to be included in step-9 of the join form during the Identity Service setup.
- As a user, I want a "Generate Chaincode" button on the chaincode generation page.
- As a user, when I click the "Generate Chaincode" button, I expect my chaincode to be created.
-  As a user, I should be able to easily copy the generated chaincode.
- As a user, I want the "Next" button to become visible after I have copied the chaincode, allowing me to proceed with next step of Identity Service Setup.

## Requirement:

Wireframe: https://excalidraw.com/#json=esi4wpGVs2StZnHBYwCEG,flkUsUctPNku40m3dzVyNA

![image](https://github.com/Real-Dev-Squad/website-www/assets/107163260/06d389ef-3d5d-407f-becc-917f3464a983)

## Acceptance Criteria:

- [ ] TDD
- [ ] The chaincode generation page is integrated into step-9 of the join form.
- [ ]  A "Generate Chaincode" button is prominently displayed on the page.
- [ ] Clicking the "Generate Chaincode" button triggers the generation of a unique chaincode.
- [ ]  Ensure that the generated chaincode is securely generated and follows any relevant security best practices.
- [ ] Users can easily copy the generated chaincode with a single click or by providing a clear and intuitive copy mechanism.
- [ ] The "Next" button becomes visible and accessible after the chaincode has been copied, enabling users to advance to the next step in the onboarding flow.
- [ ] feature under feature flag

**Comment by vinit717** [comment]
LGTM
