### ISSUE TITLE
[Live-Site] Setting up templates in 100ms

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#671]
# Setting up templates

Follow this to generate API keys first https://github.com/Real-Dev-Squad/website-www/issues/496

Visit https://dashboard.100ms.live/

- Go to templates from sidebar(as in image)
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/67a3daec-06b6-4b84-a336-86d8cb2c2ff5)

- Click on add a role button(as in image above) and add the following roles(except hls-viewer):
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/2323ea0c-79d0-4f70-bc02-e8f9429d24d4)

> Note - role names are case sensitive 

- After adding role, you can click on the role and some option will shown to you like `General` , `Publish Strategy` etc.
- Now we have to configure these for all the roles one by one.

------------
### For host

Role Priority - 1(high)

Publish strategy - only  screen will be selected here

Quality 1080p

![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/89772db7-7cec-48d6-b307-183bf76862c7)
- Subscribe strategy will be as follows:
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/21d1c50d-247f-4739-8e08-c1b404b239fa)
- Permissions will be as follows(only added enabled permissions, rest all can be disabled as of now)
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/7c895389-22eb-4b89-a320-3e7a58d9ba0f)

### For moderator

Priority will be 2

Publish strategy - no options selected

![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/d6a3e914-e2e6-4c1f-8f38-6ecf3eeb6d6d)

-Subscribe Strategy same as host
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/f1c3da7d-310e-401d-8784-75f412ea1010)

- Enabled permissions(rest all will be disabled)
- 
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/5fe4cf54-3026-4276-bdfc-a457cb465cc8)

### For maven

- These will be the `General` ,  `Publish Strategy` , `Subscribe Strategy` settings.
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/076b857f-9f3a-4afc-93ff-28b166d9ea9a)

- Enabled permissions will be:
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/b983d736-6c8e-49bd-8d36-b5962302ff77)

### For guest

- These will be the `General` ,  `Publish Strategy` , `Subscribe Strategy` settings.
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/59281090-dc06-481f-b45c-f102e25142e9)

- Enabled permissions will be :
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/69476e33-8101-4098-b0c5-e6b8ce5e6aa6)

---------
Few more steps to make it to prod:
- Please create a subdomain live.realdevsquad.com
- Redirect live.realdevsquad.com to https://beta.realdevsquad.com/live

**Comment by ankushdharkar** [comment]
Added the keys in our backend, and did all the steps listed above.
