### ISSUE TITLE
Fix: Properly Disable Join Link

### ISSUE THREAD

**Issue by ajoykumardas12** [Real-Dev-Squad/website-www#688]
### **Issue:**
Properly Disable Join Link

### **Description:**
We aren't currently accepting new join applications. The link to join RDS is currently disabled by using `pointer-events: none`, which can be easily overridden from browser devtools and then click on the link. The joining page link is also available in devtools inspect html, which can also be clicked to go to join form.

### **Solution**
The href attribute of the link should be replaced which will solve both the cases mentioned above to access the disabled link.

### **Screenshot**
![Screenshot](https://github.com/Real-Dev-Squad/website-www/assets/87164140/109ec95c-45e2-4ab2-8dff-f492474bb1d8)

**Comment by AdityaRaj2097** [comment]
I m working on it

**Comment by ajoykumardas12** [comment]
@AdityaRaj2097 Please provide Design Doc link in Issue tickets too.

**Comment by AdityaRaj2097** [comment]
https://docs.google.com/document/d/1er2FxiBekVWKPFUJITT7tNs38USn7XokSE_NJgP4_Mw/edit#heading=h.wbrbj1z3khxp
