### ISSUE TITLE
[Live-Site] Improve size of role choose card

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#697]
### Requirement
We have to fix width role choose card in `live-site` so that it looks good in terms of UI/UX

### Screenshots
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/ea0f8ff5-163b-4d2c-93c3-b3ea03a11d45)

**Comment by skt17** [comment]
ETA 18TH October

**Comment by khemchand-twt11** [comment]
ETA 20th November
