### ISSUE TITLE
[Ember-Migration] Footer Changes

### ISSUE THREAD

**Issue by khemchand-twt11** [Real-Dev-Squad/website-www#708]
## Requirements
As we are migrating our `www site` to Ember.js we need to sync our migrated site with the current version that is running on prod to be able to migrate it to Ember.js.
In this ticket we have to make the UI of footer same as in production(vanilla site).

### In vanilla site
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/f9a29bfe-dd3d-4f64-bb92-d6b04e55facb)

### In beta site(ember migrated site)
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/49f4c72d-50ad-4c5b-9410-a97725020c9c)

## Important links 
https://beta.realdevsquad.com/ (This one is made with Ember js)
https://www.realdevsquad.com/ (This one is the production site)

## Additional Notes

- Design should be same as in prod.
- Take reference from the prod site wherever needed.
- It should be responsive.
- Code quality should be maintained.

**Comment by ajoykumardas12** [comment]
I will complete this task.
**ETA:** 23rd Oct

**Comment by ajoykumardas12** [comment]
Design Doc: [Google Docs Link](https://docs.google.com/document/d/1KKaCxmqYbgSI7ZIX-xx5yOLh02r_1DDW5tJCGSUf2yQ/edit?usp=sharing)

**Comment by ajoykumardas12** [comment]
closed via #713
