### ISSUE TITLE
[Ember-Migration] Create "How to join section"

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#717]
### Requirements
As we are migrating towards Emberjs we need the given section to be sync with our production, to look it exactly like production version. In this ticket we have to make the mentioned section UI as well as functionalities to match same as in production version.

#### In vanilla site (currently running www site in production, created with plain HTML, CSS, JS)
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/12121f71-183a-4234-833a-4160db8925a3)

#### In beta site(created with EmberJS)
![image](https://github.com/Real-Dev-Squad/website-www/assets/85296770/be2322c0-ab99-4b11-82ac-925b7b990fdd)

### Important links

- https://beta.realdevsquad.com/ (This one is made with Ember js)
- https://www.realdevsquad.com/ (This one is the production site)

### Additional Note

- Design should be same as in prod.
- Take reference from the prod site wherever needed.
- It should be responsive.
- Code quality should be maintained.

### Questions you can have in mind

1. Is this should be under feature flag?
Yes, it should be under feature dev=true

2. What is feature flag?
It's a simple variable which we can use to turn off/on the feature. Currently we use dev=true in URL query.

3. Do you have to use the same code as in production site?
No, the solution is upto you how you want to approach the problem. It should be same UI wise and functionality wise, rest other implementation is on you.

4. In which branch ember code is in?
It's in `develop-ember` branch, make sure to checkout to that branch.

**Comment by suryxks** [comment]
@satyam73  can you please assign this to me
