### ISSUE TITLE
[UI]: Navbar pills not aligned

### ISSUE THREAD

**Issue by samyakshah3008** [Real-Dev-Squad/website-www#718]
## Description: 

- Nav-pills on the left are aligned to top. I see the right part's pill is aligned to center and making it inconsistent across the navbar. To make consistent UI, let's have all the pills aligned to center. 

## Screenshot which displays the bug: 

![image](https://github.com/Real-Dev-Squad/website-www/assets/86982322/49f79cc2-8c63-44ef-9eb0-74505653f517)

## Fixed bug screenshot: 

![image](https://github.com/Real-Dev-Squad/website-www/assets/86982322/c456c21e-cda0-4ba1-bba6-9e79a4f2c5b0)

**Comment by satyam73** [comment]
Closing this since we've migrated our site to Ember and this issue was opened for Vanilla site
