### ISSUE TITLE
[Ember-Migration] Create Debug page

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#738]
### Requirements
As we are migrating towards Emberjs we need the given section to be sync with our production, to look it exactly like production version. In this ticket we have to make the mentioned section UI as well as functionalities to match same as in production version.

#### In vanilla site (currently running www site in production, created with plain HTML, CSS, JS)
Debug page -  https://www.realdevsquad.com/debug

#### In beta site(created with EmberJS)
Doesn't exists

### Important links

- https://staging-www.realdevsquad.com/ (This one is made with Ember js, staging one)
- https://www.realdevsquad.com/ (This one is the production site)

### Additional Note

- Design should be same as in prod.
- Take reference from the prod site wherever needed.
- It should be responsive.
- Code quality should be maintained.
- Use `ember generate` commands to generate `components`, `templates` and other files.

### Questions you can have in mind

1. Is this should be under feature flag?
Yes, it should be under feature dev=true

2. What is feature flag?
It's a simple variable which we can use to turn off/on the feature. Currently we use dev=true in URL query.

3. Do you have to use the same code as in production site?
No, the solution is upto you how you want to approach the problem. It should be same UI wise and functionality wise, rest other implementation is on you.

4. In which branch ember code is in?
It's in `develop-ember` branch, make sure to checkout to that branch.

**Comment by gauravsinhaweb** [comment]
ETA: October 17th, 2023 (End of Day)

Milestones:
- Review Ember documentation and familiarize yourself with the codebase - Deadline: October 8th, 2023
- Write code for the Ember migration - Deadline: October 9th, 2023
- Write code for the Ember migration, write test cases, and review Ember testing documentation - Deadline: October 13th, 2023
- Write additional tests and make necessary code changes; perform sanity testing - Deadline: October 14th, 2023
- Push the code for review - Deadline: October 15th, 2023
- Address any comments or feedback received during the review phase - Deadline: October 16th, 2023
- Finalize any remaining reviewer comments and conclude the review phase - Deadline: October 17th, 2023
