### ISSUE TITLE
Provide link to website-static for image upload

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-www#76]
We want our user-form to show a link to our website-static repo to complete image upload process

**Comment by Khanjan04** [comment]
I have created the PR. Do let me know if changes are required

**Comment by ankushdharkar** [comment]
Awesome. I can see the link.
![image](https://user-images.githubusercontent.com/1935403/100644032-a6168b80-32ef-11eb-8a19-ff34fb3e5d3a.png)
