### ISSUE TITLE
Add some margin around Sign in button

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-www#83]
Add a good margin for both, Desktop and Mobile, for the sign in button

![unknown](https://user-images.githubusercontent.com/1935403/102040645-363de180-3d82-11eb-950e-8f4ae46ed6f8.png)

**Comment by adnanraghib1308** [comment]
Can i work on this issue?? @ankushdharkar

**Comment by ankushdharkar** [comment]
Sure @adnanraghib1308

Also, if you haven't already, join our Discord server

**Comment by ankushdharkar** [comment]
Thank you @adnanraghib1308! 🎉 
Approved and merged!
