### ISSUE TITLE
Pre fill name for host and moderator(when logged in)

### ISSUE THREAD

**Issue by satyam73** [Real-Dev-Squad/website-www#865]
### Issue Description

We need to prefill the input of name if the user is logged in, in live site. It will make better UI/UX experience for the user since they don't have to enter name everytime when they're logged in.

### Expected Behavior

We need to prefill the input of name if the user is logged in, in live site. It will make better UI/UX experience for the user since they don't have to enter name everytime when they're logged in.

### Current Behavior

We have to enter name manually if we have to enter the live event.

### Screenshots

n/a

### Reproducibility

 - [x] This issue is reproducible
-  [ ] This issue is not reproducible

### Steps to Reproduce
- Go to /live with dev=true feature flag to see the issue

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

**Comment by jsuryakt** [comment]
@satyam73 Can you assign this to me
