### ISSUE TITLE
Enhance /intro Page with Application Status, Feedback, and Discord Invite Link

### ISSUE THREAD

**Issue by vinit717** [Real-Dev-Squad/website-www#903]
## Issue Description
After a new user submits the join form, they receive a personalized link to check the status of their application. This link should direct them to the /intro page, formatted as `/intro?id=<user_id>&status=submitted`. The /intro page should display the application status and any feedback provided by a superuser and if the application is approved user can view discord invite link, otherwise that their application was not approved.

### Behavior for Different Users:

- ### New Users:
When a new user visits the /intro page using their personalized link, they see the status of their application. Depending on the status:

   - Pending:
     The page displays a message asking them to wait until their application is reviewed.
     `We are reviewing your application. Please check again here periodically for an update.`
     
   - Approved:
     The page provides a Discord invite link, allowing them to join the server.
     `Congratulations. You've been approved to join our Discord server using this link: <Link>`

   - Rejected:
     The page shows the rejection message and any feedback provided by the superuser.
      `Unfortunately, at this time, your application is not approved.`

     
- ### Superusers:
If a superuser accesses the personalized link, they should be redirected to the dashboard application page at https://dashboard.realdevsquad.com/applications?id=<user_id> where they can review and update the application status.

## Expected Behavior

- New users receive a personalized link after submitting the join form and can use it to check their application status on the /intro page.
- The /intro page shows different content based on the application status:
    - If the application is under review, a waiting message is displayed.
    - If the application is approved, a Discord invite link is shown.
    - If the application is rejected, a rejection message and feedback are displayed.
- Superusers are automatically redirected to the dashboard's application page (https://dashboard.realdevsquad.com/applications?id=<user_id>) when they visit the personalized link.

### Steps to Reproduce
1. A new user fills out and submits the join form.
2. The user receives a personalized link (e.g., /intro?id=<user_id>&status=submitted) and uses it to check their application status.
3. If the user is a superuser, visiting the link redirects them to https://dashboard.realdevsquad.com/applications?id=<user_id>.
4. If the user is not a superuser, they stay on the /intro page and see the relevant application status and feedback.
5. If the super user approves the application user can discord the invite link on that page.

### Severity/Priority
 - [x] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Additional Information
- The Discord invite link is only provided on the /intro page when the application is approved.
- Superusers update the application status and provide feedback through the dashboard, not directly on the /intro page and the status and feedback if provided should reflect on the intro page.

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

**Comment by ankushdharkar** [comment]
Requirements look good @vinit717. Thanks!
