### ISSUE TITLE
Test server not working

### ISSUE THREAD

**Issue by tejaskh3** [Real-Dev-Squad/website-www#937]
### Issue Description
The test server for ember is not working fine, we tested that on chrome and brave browser.
The issue is after running all the 
cc: @satyam73  @lakshayman 

### Expected Behavior
It should stop after running one time.

### Screenshots
[screen-capture (21).webm](https://github.com/user-attachments/assets/660deca2-6e97-487f-b53a-eb400492c94c)

### Severity/Priority
 - [ ] Critical
 - [x] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by iamitprakash** [comment]
Hello @tejaskh3 are you sure. this is the same case happening with others as well

**Comment by tejaskh3** [comment]
I am not sure about it right now, but will let you know once I confirm this by reciprocating the same issue in someone else system.

**Comment by satyam73** [comment]
@tejaskh3 please check in develop branch once if it's happening, for me it's not happening

**Comment by tejaskh3** [comment]
for me also this is working fine, so I am closing this issue.
